# Generated by Django 3.2.9 on 2021-11-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('longitude', models.CharField(max_length=250)),
                ('latitutde', models.CharField(max_length=250)),
                ('google_maps_link', models.URLField()),
                ('primary_contact', models.CharField(max_length=250)),
                ('secondary_contact', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
            },
        ),
    ]
