# Generated by Django 3.2.9 on 2021-11-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default=None, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=250)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.locations')),
            ],
            options={
                'verbose_name_plural': 'Floor Plan',
                'db_table': 'floor_plan',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_for_date', models.DateField(default=None)),
                ('booking_reference_number', models.CharField(max_length=50)),
                ('lunch_type', models.CharField(default=None, max_length=50)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.locations')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.floorplan')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
            },
        ),
    ]
