# Generated by Django 3.2.9 on 2021-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_booking_employee_floorplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lunch_type',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
