# Generated by Django 3.2.9 on 2021-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_booking_lunch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='floor',
            field=models.CharField(choices=[('', '---'), ('floor1', 'Floor 1'), ('floor2', 'Floor 2'), ('floor3', 'Floor 3'), ('floor4', 'Floor 4'), ('floor5', 'Floor 5')], max_length=10),
        ),
    ]
