# Generated by Django 3.2.9 on 2021-11-27 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_floorplan_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='booking_by', to='backend.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_for', to='backend.employee'),
        ),
    ]
